-- 기술필터
DROP TABLE SKILL_FILTER;
CREATE TABLE SKILL_FILTER(
    
    SKILL VARCHAR2(20) UNIQUE
);

-- 경력필터
DROP TABLE CAREER_FILTER;
CREATE TABLE CAREER_FILTER (
    
    CAREER VARCHAR2(20) UNIQUE
);

-- 지역필터
DROP TABLE REGION_FILTER;
CREATE TABLE REGION_FILTER(
    
    REGION VARCHAR(20) UNIQUE
);

--=============================================================================

-- 개인회원_가입정보
DROP TABLE USERS;
CREATE TABLE USERS (
    USER_ID varchar2(320) PRIMARY KEY,
    USER_NAME varchar2(30) not null,
    USER_PW varchar2(50)  not null,
    USER_TELL varchar2(50) not null,
    USER_BIRTH DATE NOT NULL,
    USER_ADR VARCHAR2(50) NOT NULL,
    USER_DATE date DEFAULT SYSDATE
);

-- 개인회원_이력서
DROP TABLE RESUME;
CREATE TABLE RESUME (
    RE_NUM NUMBER(20) PRIMARY KEY,
    USER_ID VARCHAR2(320), 
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE, 
    RE_TITLE VARCHAR2(320) NOT NULL,
    SKILL VARCHAR2(20),
    FOREIGN KEY (SKILL) REFERENCES SKILL_FILTER(SKILL) ON DELETE CASCADE,
    CAREER VARCHAR2(20),
    FOREIGN KEY (CAREER) REFERENCES CAREER_FILTER(CAREER) ON DELETE CASCADE,
    REGION VARCHAR2(20),
    FOREIGN KEY (REGION) REFERENCES REGION_FILTER(REGION) ON DELETE CASCADE,
    USER_EDU VARCHAR2(50),
    USER_CAR VARCHAR2(50) NOT NULL,
    USER_INTRO VARCHAR2(4000) NOT NULL,
    USER_IMG VARCHAR2(50)
);



--=============================================================================


-- 기업회원_가입정보
DROP TABLE COMPANY;
CREATE TABLE COMPANY (
    COM_ID VARCHAR2(320) PRIMARY KEY,
    COM_PW VARCHAR2(20) NOT NULL,
    COM_NAME VARCHAR2(20) NOT NULL,
    COM_NUM VARCHAR2(30) NOT NULL,
    COM_BOSS VARCHAR2(20) NOT NULL,
    COM_ADR VARCHAR2(20) NOT NULL,
    COM_TELL VARCHAR2(50) NOT NULL,
    COM_DATE DATE DEFAULT SYSDATE
);

-- 채용공고
DROP TABLE POST;
CREATE TABLE POST (
    PO_NUM NUMBER(20) PRIMARY KEY,
    COM_ID VARCHAR2(320),
      FOREIGN KEY (COM_ID) REFERENCES COMPANY(COM_ID) ON DELETE CASCADE,
    PO_TITLE VARCHAR2(50) NOT NULL,
    SKILL VARCHAR2(20),
      FOREIGN KEY (SKILL) REFERENCES SKILL_FILTER(SKILL) ON DELETE CASCADE,
    CAREER VARCHAR2(20),
      FOREIGN KEY (CAREER) REFERENCES CAREER_FILTER(CAREER) ON DELETE CASCADE,
    REGION VARCHAR2(20),
      FOREIGN KEY (REGION) REFERENCES REGION_FILTER(REGION) ON DELETE CASCADE,
    PO_QUAL VARCHAR2(320),
    PO_CONTENT VARCHAR2(320),
    PO_IMAGE VARCHAR2(100)
);

-- 기업회원_이력서 스크랩
DROP TABLE COMBOOK;
CREATE TABLE COMBOOK (
    RE_NUM NUMBER(10),
     FOREIGN KEY (RE_NUM) REFERENCES RESUME(RE_NUM) ON DELETE CASCADE,
    COM_ID VARCHAR2(320),
      FOREIGN KEY (COM_ID) REFERENCES COMPANY(COM_ID) ON DELETE CASCADE,
    --USER_ID VARCHAR2(320),
    --  FOREIGN KEY (RE_NUM) REFERENCES RESUME(RE_NUM),
    CB_NUM NUMBER(20) PRIMARY KEY,
    CB_BOOLEAN NUMBER(1)
);


-- 개인회원_공고스크랩
DROP TABLE USERBOOK;
CREATE TABLE USERBOOK (
    PO_NUM NUMBER(10),
      FOREIGN KEY (PO_NUM) REFERENCES POST(PO_NUM) ON DELETE CASCADE,
    USER_ID VARCHAR2(320),
      FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    UB_NUM NUMBER(20) PRIMARY KEY,
    UB_BOOLEAN NUMBER(1)
);




-- 개인회원_입사지원관리
DROP TABLE APPLY;
CREATE TABLE APPLY (
    AP_ID NUMBER(20) PRIMARY KEY,                 -- 지원 번호
    PO_NUM NUMBER(20),                                      -- 공고 번호
      FOREIGN KEY (PO_NUM) REFERENCES POST(PO_NUM) ON DELETE CASCADE,
    RE_NUM NUMBER(20),                                      -- 이력서 번호
      FOREIGN KEY (RE_NUM) REFERENCES RESUME(RE_NUM) ON DELETE CASCADE,
    RE_TITLE VARCHAR2(320),                                   -- 이력서 제목
    --  FOREIGN KEY (RE_TITLE) REFERENCES RESUME(RE_TITLE),
    PO_TITLE VARCHAR2(320),                                  -- 공고 제목
    RESULT NUMBER(3),                                       -- 합격/불합격/진행중
    AP_DATE DATE DEFAULT SYSDATE                           
);

-- 면접 제안
DROP TABLE APPLY2;
CREATE TABLE APPLY2 (
    AP_ID NUMBER(20) PRIMARY KEY,                 --  번호
    PO_NUM NUMBER(20),                                      -- 공고 번호
      FOREIGN KEY (PO_NUM) REFERENCES POST(PO_NUM) ON DELETE CASCADE,
    RE_NUM NUMBER(20),                                      -- 이력서 번호
      FOREIGN KEY (RE_NUM) REFERENCES RESUME(RE_NUM) ON DELETE CASCADE,
    RE_TITLE VARCHAR2(320),                                   -- 이력서 제목
    PO_TITLE VARCHAR2(320),                                  -- 공고 제목
    RESULT NUMBER(3),                                       -- 
    AP_DATE DATE DEFAULT SYSDATE                           
);



--=============================================================================


-- 유저 커뮤니티
DROP TABLE U_COMMUNITY;
CREATE TABLE U_COMMUNITY(
    UCOMU_BNO NUMBER(20) PRIMARY KEY,
    UCOMU_TITLE VARCHAR2(50) NOT NULL,
    UCOMU_CONTENT VARCHAR2(1000),
    USER_ID VARCHAR2(20),
      FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    UCOMU_HIT NUMBER(20) DEFAULT 0,
    UCOMU_DATE DATE DEFAULT SYSDATE
);

-- 유저커뮤니티 댓글 테이블
DROP TABLE U_COMMENTS;
CREATE TABLE U_COMMENTS (
    UCOMU_BNO NUMBER(20),                   -- 커뮤니티 글번호
      FOREIGN KEY (UCOMU_BNO) REFERENCES U_COMMUNITY (UCOMU_BNO) ON DELETE CASCADE,
    UCOMM_ID  NUMBER(20) PRIMARY KEY,                   -- 댓글 식별자
    UCOMM_BODY VARCHAR2(1000) NOT NULL,     -- 댓글 내용
    USER_ID  VARCHAR2(320) NOT NULL,        -- 댓글 작성자
      FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE,
    UCOMU_GOOD NUMBER(2)                    -- 댓글 좋아요 싫어요
);

-- 기업 커뮤니티
DROP TABLE C_COMMUNITY;
CREATE TABLE C_COMMUNITY(
    CCOMU_BNO NUMBER(20) PRIMARY KEY,
    CCOMU_TITLE VARCHAR2(50) NOT NULL,
    CCOMU_CONTENT VARCHAR2(1000),
    COM_ID VARCHAR2(20),
      FOREIGN KEY (COM_ID) REFERENCES COMPANY(COM_ID) ON DELETE CASCADE,
    CCOMU_HIT NUMBER(20) DEFAULT 0,
    CCOMU_DATE DATE DEFAULT SYSDATE
);

-- 기업커뮤니티 댓글 테이블
DROP TABLE C_COMMENTS;
CREATE TABLE C_COMMENTS (
    CCOMU_BNO NUMBER(20),                   -- 커뮤니티 글번호
      FOREIGN KEY (CCOMU_BNO) REFERENCES C_COMMUNITY (CCOMU_BNO) ON DELETE CASCADE,
    CCOMM_ID  NUMBER(20) PRIMARY KEY,                   -- 댓글 식별자
    CCOMM_BODY VARCHAR2(1000) NOT NULL,     -- 댓글 내용
    COM_ID  VARCHAR2(320) NOT NULL,         -- 댓글 작성자
      FOREIGN KEY (COM_ID) REFERENCES COMPANY (COM_ID) ON DELETE CASCADE,
    CCOMU_GOOD NUMBER(2)                    -- 댓글 좋아요 싫어요
);




--============================================================================


-- 구직자-기업평점 테이블
DROP TABLE COMRATINGS;
CREATE TABLE COMRATINGS (
    RATING_ID NUMBER(10) PRIMARY KEY,   -- PK 평점 식별자
    COM_ID VARCHAR2(320),               -- FK 평가된 기업의 식별자
      FOREIGN KEY (COM_ID) REFERENCES COMPANY (COM_ID) ON DELETE CASCADE,
    USER_ID VARCHAR2(320),              -- FK 평가를 남긴 구직자의 식별자
      FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE,
    RATING NUMBER(5) NOT NULL      
);

-- 기업-구직자평점 테이블
DROP TABLE USERRATINGS;
CREATE TABLE USERRATINGS (
    RATING_ID NUMBER(10) PRIMARY KEY,   -- PK 평점 식별자
    USER_ID VARCHAR2(320),              -- FK 평가된 구직자의 식별자
      FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE,
    COM_ID VARCHAR2(320),               -- FK 평가를 남긴 기업의 식별자
      FOREIGN KEY (COM_ID) REFERENCES COMPANY (COM_ID) ON DELETE CASCADE,
    RATING NUMBER(5) NOT NULL         
);

-- 기업-커뮤니티-댓글 좋아요 테이블
DROP TABLE C_COMMENTS_LIKE;
CREATE TABLE C_COMMENTS_LIKE (
   COMMENT_LIKE_BNO NUMBER(20) PRIMARY KEY,   -- PK 평점 식별자
   CCOMU_BNO NUMBER(20) NOT NULL,         -- 게시물 번호
   FOREIGN KEY (CCOMU_BNO) REFERENCES C_COMMUNITY (CCOMU_BNO) ON DELETE CASCADE,
   CCOMM_ID  NUMBER(20) NOT NULL,         -- 댓글 번호
   FOREIGN KEY (CCOMM_ID) REFERENCES C_COMMENTS (CCOMM_ID) ON DELETE CASCADE,
   COM_ID  VARCHAR2(320) NOT NULL,        -- 좋아요 누른 사람
   FOREIGN KEY (COM_ID) REFERENCES COMPANY (COM_ID) ON DELETE CASCADE
);

-- 개인-커뮤니티-댓글 좋아요 테이블
DROP TABLE U_COMMENTS_LIKE;
CREATE TABLE U_COMMENTS_LIKE (
   COMMENT_LIKE_BNO NUMBER(20) PRIMARY KEY,   -- PK 평점 식별자
   UCOMU_BNO NUMBER(20) NOT NULL,         -- 게시물 번호
   FOREIGN KEY (UCOMU_BNO) REFERENCES U_COMMUNITY (UCOMU_BNO) ON DELETE CASCADE,
   UCOMM_ID  NUMBER(20) NOT NULL,         -- 댓글 번호
   FOREIGN KEY (UCOMM_ID) REFERENCES U_COMMENTS (UCOMM_ID) ON DELETE CASCADE,
   USER_ID  VARCHAR2(320) NOT NULL,        -- 좋아요 누른 사람
   FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);
-- NOTIFICTION
DROP TABLE NOTIFICATIONS;
CREATE TABLE NOTIFICATIONS (
    NO_ID NUMBER(3) PRIMARY KEY,
    USER_ID VARCHAR2(320),
      FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    COM_ID VARCHAR2(320),
      FOREIGN KEY (COM_ID) REFERENCES COMPANY(COM_ID) ON DELETE CASCADE,
    PO_NUM NUMBER(20),
      FOREIGN KEY (PO_NUM) REFERENCES POST(PO_NUM) ON DELETE CASCADE,
    RE_NUM NUMBER(20),
      FOREIGN KEY (RE_NUM) REFERENCES RESUME(RE_NUM) ON DELETE CASCADE,
    ISREAD NUMBER(1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
-- OFFER
DROP TABLE OFFER;
CREATE TABLE OFFER (
    OF_ID NUMBER(3) PRIMARY KEY,
    PO_NUM NUMBER(20),                                      -- 공고 번호
      FOREIGN KEY (PO_NUM) REFERENCES POST(PO_NUM) ON DELETE CASCADE,
    RE_NUM NUMBER(20),                                      -- 이력서 번호
      FOREIGN KEY (RE_NUM) REFERENCES RESUME(RE_NUM) ON DELETE CASCADE,
    RE_TITLE VARCHAR2(320),                                   -- 이력서 제목
    --  FOREIGN KEY (RE_TITLE) REFERENCES RESUME(RE_TITLE),
    PO_TITLE VARCHAR2(320),                                  -- 공고 제목
    RESULT NUMBER(3),                                       -- 합격/불합격/진행중
    OF_DATE DATE DEFAULT SYSDATE                           
);



commit;